### ISSUE TITLE
Add backup schedule to compose

### ISSUE THREAD

**Issue by dudizimber** [FalkorDB/falkordb-omnistrate#24]
``` 
x-omnistrate-capabilities:
  backupConfiguration:
    backupRetentionInDays: 7
    backupPeriodInHours: 12
```
